version: '3.8'

services:
  client:
    container_name: client
    build: ./client
    restart: always
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    container_name: server
    restart: always
    volumes:
      - log:/log
    ports:
      - "8000:8000"
    env_file:
      - .env
    build: ./server
    command: npm run dev
    depends_on:
      - mongodb
  mongodb:
    restart: always
    container_name: mongo
    env_file:
      - .env
    image: mongo:6.0.2
    volumes:
      - mongo:/data/db
  mongo-seed:
    env_file:
      - .env
    build: ./database
    depends_on:
      - mongodb
volumes:
  log:
  mongo: